// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using happyshop.Data;

#nullable disable

namespace happyshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("happyshop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2023, 11, 5, 18, 1, 19, 441, DateTimeKind.Local).AddTicks(3183),
                            DisplayOrder = 1,
                            Name = "Tech"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2023, 11, 5, 18, 1, 19, 441, DateTimeKind.Local).AddTicks(3200),
                            DisplayOrder = 2,
                            Name = "wood"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2023, 11, 5, 18, 1, 19, 441, DateTimeKind.Local).AddTicks(3201),
                            DisplayOrder = 3,
                            Name = "interior"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2023, 11, 5, 18, 1, 19, 441, DateTimeKind.Local).AddTicks(3203),
                            DisplayOrder = 4,
                            Name = "extrior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
